In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
X = df.drop("sales", axis=1)

In [4]:
y = df["sales"]

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynormial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [7]:
poly_features = polynormial_converter.fit_transform(X)

In [8]:
poly_features.shape

(200, 19)

In [20]:
# Scaling

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [11]:
X_train.shape

(140, 19)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
scaled_X_train = scaler.transform(X_train)

In [16]:
scaled_X_test = scaler.transform(X_test)

In [19]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [18]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
# Ridge Regression | Shrinkage penalty

In [22]:
from sklearn.linear_model import Ridge

In [23]:
ridge_model = Ridge(alpha=10)

In [24]:
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [25]:
test_predictions = ridge_model.predict(scaled_X_test)

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [27]:
MAE = mean_absolute_error(y_test, test_predictions)

In [28]:
MAE

0.5774404204714177

In [29]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [30]:
RMSE

0.894638646131968

In [31]:
from sklearn.linear_model import RidgeCV

In [32]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10))

In [33]:
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(alphas=(0.1, 1.0, 10))

In [34]:
ridge_cv_model.alpha_

0.1

In [36]:
#from sklearn.metrics import SCORERS

In [37]:
test_predictions = ridge_cv_model.predict(scaled_X_test)

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)

In [39]:
MAE

0.42737748843373746

In [40]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [41]:
RMSE

0.6180719926921404

In [43]:
# LASSO Regularization | least absolute shrinkage and selection operator

In [44]:
from sklearn.linear_model import LassoCV

In [65]:
lasso_cv_model = LassoCV(max_iter=100000)

In [66]:
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(max_iter=100000)

In [67]:
lasso_cv_model.alpha_

0.004943070909225827

In [68]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [69]:
MAE = mean_absolute_error(y_test, test_predictions)

In [70]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [71]:
MAE

0.43350346185900673

In [72]:
RMSE

0.6063140748984039

In [73]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [74]:
# Elastic Net

In [75]:
from sklearn.linear_model import ElasticNetCV

In [76]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=100000)

In [77]:
elastic_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [78]:
elastic_model.l1_ratio_

1.0

In [80]:
test_predictions = elastic_model.predict(scaled_X_test)

In [81]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [83]:
MAE

0.43350346185900673

In [84]:
RMSE

0.6063140748984039